name: Swift

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.7.0"
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build -Xswiftc -enable-bare-slash-regex
      - name: Run tests
        run: swift test
