name: test

on:
  pull_request:

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4
      - name: Set Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_15.4.app/Contents/Developer'
      - name: Run tests
        run: swift test
